### PR TITLE
GH Action

### LINKED ISSUE #1: Editing a file won't work either :)
Editing a file won't be saved on vercel either.. unless you can somehow [dispatch a GitHub Workflow thing that updates the file via the API](https://docs.github.com/en/rest/reference/actions#create-a-workflow-dispatch-event)

### PR DESCRIPTION
**Pull request by liimee**
I haven't tried running it through the API though

also sorry for the 19 commits hehe

resolves #1

### CODE REVIEW

**Comment by liimee** [comment]
also make sure to edit the name and email (make sure it's not the public one)

and also add a 'TEST' secret that contains your token

**Comment by liimee** [comment]
doing
```js
var xhr = new XMLHttpRequest();
xhr.open("POST", 'https://api.github.com/repos/liimee/request-counter/actions/workflows/rickroll.yml/dispatches');

xhr.setRequestHeader("Authorization", "Bearer sometokenhere");
xhr.setRequestHeader("Content-Type", "application/json");

xhr.onreadystatechange = function () {
   if (xhr.readyState === 4) {
      console.log(xhr.status);
      console.log(xhr.responseText);
   }
};

xhr.send('{"ref": "main"}');
```
apparently works

**Comment by Electogenius** [comment]
Yeeee!

I’ll just merge this and I’ll change the details in a bit, I’m busy procrastinating

**Comment by Electogenius** [comment]
Oops

**Pull request merged**
